# List all metafor functions and capabilities
library(metafor)

cat("=== METAFOR EXPORTED FUNCTIONS ===\n\n")
fns <- ls("package:metafor")
for (fn in fns) {
  cat(fn, "\n")
}
cat("\nTotal functions:", length(fns), "\n")

cat("\n=== KEY FUNCTION CATEGORIES ===\n\n")

cat("Effect Size Calculations (escalc measures):\n")
cat("  Binary: OR, RR, RD, AS, PETO, PHI, YUQ, YUY, RTET, PBIT, OR2D, OR2DN, OR2DL\n")
cat("  Continuous: MD, SMD, SMDH, ROM\n")
cat("  Correlations: COR, UCOR, ZCOR\n")
cat("  Proportions: PR, PLN, PLO, PAS, PFT\n")
cat("  IRR: IR, IRLN, IRS, IRFT\n")
cat("  Mean: MN, MNLN, MC, SMCC, SMCR, SMCRH, ROMC, CVRC, VRC\n")
cat("  Other: ARAW, AHW, ABT\n")

cat("\nModel Fitting (rma methods):\n")
cat("  FE, EE, CE (fixed effects)\n")
cat("  DL, HE, HS, HSk, SJ, ML, REML, EB, PM, GENQ, PMM, GENQM\n")

cat("\nHeterogeneity Tests:\n")
cat("  Q statistic, I2, H2, tau2\n")
cat("  confint() for tau2 CI\n")

cat("\nPublication Bias:\n")
cat("  regtest() - Egger regression\n")
cat("  ranktest() - Begg rank correlation\n")
cat("  trimfill() - Trim and fill\n")
cat("  fsn() - Fail-safe N (Rosenthal, Orwin, Rosenberg)\n")
cat("  selmodel() - Selection models (beta, halfnorm, negexp, logistic, power, stepfun)\n")
cat("  tes() - Test of excess significance\n")

cat("\nSensitivity Analysis:\n")
cat("  leave1out() - Leave-one-out\n")
cat("  cumul() - Cumulative meta-analysis\n")
cat("  influence() - Influence diagnostics\n")
cat("  gosh() - GOSH plot analysis\n")

cat("\nMultilevel/Multivariate:\n")
cat("  rma.mv() - Multivariate/multilevel models\n")
cat("  rma.uni() - Univariate models\n")
cat("  rma.glmm() - Generalized linear mixed models\n")
cat("  rma.mh() - Mantel-Haenszel method\n")
cat("  rma.peto() - Peto method\n")

cat("\nPlotting:\n")
cat("  forest() - Forest plots\n")
cat("  funnel() - Funnel plots\n")
cat("  radial() - Radial/Galbraith plots\n")
cat("  baujat() - Baujat plots\n")
cat("  labbe() - L'Abbe plots\n")
cat("  inflfun() - Influence function plots\n")
cat("  plot.gosh.rma() - GOSH plots\n")
cat("  qqnorm() - QQ plots\n")
cat("  profile() - Profile likelihood plots\n")

cat("\nMeta-Regression:\n")
cat("  rma() with mods argument\n")
cat("  anova() for model comparison\n")
cat("  predict() for predictions\n")
cat("  robust() for cluster-robust inference\n")

cat("\nAdvanced:\n")
cat("  fitstats() - Model fit statistics (AIC, BIC, etc.)\n")
cat("  weights() - Study weights\n")
cat("  coef(), vcov() - Coefficients and variance-covariance\n")
cat("  residuals(), rstandard(), rstudent() - Residuals\n")
cat("  hatvalues(), cooks.distance(), dfbetas() - Influence measures\n")
cat("  blup() - Best linear unbiased predictions\n")
cat("  ranef() - Random effects\n")
cat("  simulate() - Simulate data from model\n")
cat("  permutest() - Permutation tests\n")
cat("  vif() - Variance inflation factors\n")
cat("  reporter() - Generate analysis reports\n")
